spring:
  application:
    name: delivery-api
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: create
  datasource:
    username: root
    password: 12345678
    url: jdbc:mysql://localhost:3306/food_delivery?useSSL=false&serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
  devtools:
    livereload:
      enabled: false